### ISSUE TITLE
Ability to query active listings and offers

### ISSUE THREAD

**Issue by 0xAlcibiades** [Alcibiades-Capital/quay#15]
See: https://docs.opensea.io/v2.0/reference/retrieve-listings and https://docs.opensea.io/v2.0/reference/retrieve-offers

**Comment by Amenacliff** [comment]
Interested in working on this @0xAlcibiades

**Comment by 0xAlcibiades** [comment]
> Interested in working on this @0xAlcibiades

I know @perpetuum7 has something coming down the pike for this. Might be helpful if we loop you in on the PR.
