### ISSUE TITLE
Migrate Quay to Axum

### ISSUE THREAD

**Issue by 0xAlcibiades** [Alcibiades-Capital/quay#35]
Migrating from actix -> axum is in line with getting everything running on the tokio runtime, as well as the ability to support a hybrid server for gRPC and http on the same port.

**Comment by perpetuum7** [comment]
Next up, the removal of Actix sessions by @0xAlcibiades.

**Comment by 0xAlcibiades** [comment]
This is being tracked here: https://github.com/Alcibiades-Capital/quay/pull/41, I've tagged v0.1.0, so we can merge back to master once we get back to feature parity. Though, because we are changing the orders API, this is going to look more like a 1.0.0 release when it's done.
